name: Automated API tests using Postman CLI

on: push

jobs:
  automated-linting-of-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Validate Spec
        run: |
          postman spec lint 80771b57-80b9-4b3f-a016-33a251b51385 --fail-severity error
